### ISSUE TITLE
Custom "API Confluence" page views causing performance problems

### ISSUE THREAD

**Issue by mdittmer** [GoogleChromeLabs/confluence#102]
Creating custom views by interacting with confluence graphs (except for API Velocity, they are okay) triggers an expensive query and data rehashing procedure.

The real problem here is that the client-side part (data caching and rehashing) is done largely synchronously on the same worker that serves all other data queries. Hence, attempting to load a custom confluence view, then navigating to the catalog view yields an empty table. Returning to the confluence view yields no graphs (because they also query via the worker for their data).

**Comment by mdittmer** [comment]
@foolip @drufball what would you think about disabling these custom views for now? The downside there is that we cannot surface "proof" that the API counts are correct via the UI.

Another alternative (which I have sitting on a branch somewhere) is to make the views open in a new window. The downside there is that we don't benefit from caching (since we're not using a shared or service worker). On the other hand, it keeps the UI in each window from locking up due to resource starvation on the worker.

WDYT?

**Comment by foolip** [comment]
Are custom views when you pick a set of browsers other than the default?

**Comment by mdittmer** [comment]
No. If you click a point on one of the metrics graphs, an overlay includes
a link next to the number written in the overlay. Clicking the link opens a
new web UI tab (alongside Aggressive Removal, etc.) Showing all the
relevant browsers to verify the metric is correct, and only the APIs
included in the count from the graph. The main value here is seeing what
the APIs that constitute the metric are.

**Comment by foolip** [comment]
Oh, I see, pretty cool! Disabling that for the initial launch should be fine though, it'll still be possible to verify the correctness by other means.

**Comment by mdittmer** [comment]
This is improved by https://github.com/GoogleChrome/confluence/pull/106 but could still benefit from better loading+caching strategies.

**Comment by foolip** [comment]
I'd say performance is good enough now.
