### ISSUE TITLE
Implausible removals claimed between Chrome 53.0.2785.101 and 53.0.2785.113 on Windows 10.0

### ISSUE THREAD

**Issue by foolip** [GoogleChromeLabs/confluence#122]
Can be seen at http://web-confluence.appspot.com/#!/catalog?releaseKeys=%5B%22Chrome_53.0.2785.113_Windows_10.0%22,%22Chrome_53.0.2785.101_Windows_10.0%22%5D&releaseOptions=%7B%22Chrome_53.0.2785.113_Windows_10.0%22:true,%22Chrome_53.0.2785.101_Windows_10.0%22:false%7D&numAvailable=null&currentPage=0&gap=5&itemPerPage=15&searchKey=%22%22

It claims that lots of things on CSSStyleDeclaration have changed.

**Comment by foolip** [comment]
This is from http://web-confluence.appspot.com/#!/confluence, at what looks like removal and adding back in in July-October. Seems like there are differences between Chrome 53.0.2785.101 Windows 10.0 and Chrome 53.0.2785.113 Windows 10.0 that probably aren't true.

**Comment by jpmedley** [comment]
53.0.2785.101 is not currently in the release list, so no way to investigate.
