### ISSUE TITLE
Can we get rid of the pagination?

### ISSUE THREAD

**Issue by foolip** [GoogleChromeLabs/confluence#166]
Since we can expand interfaces, one often has to scroll, but we also have pagination. Could we always use a single page instead?

Probably wouldn't fix https://github.com/GoogleChrome/confluence/issues/165 but may be related.

**Comment by mdittmer** [comment]
That seems feasible. Something like [this](https://material.angularjs.org/latest/api/directive/mdVirtualRepeat) should do the trick.

**Comment by foolip** [comment]
Pagination is long gone!
