### ISSUE TITLE
Idea: have a standardization status (bool) for each API

### ISSUE THREAD

**Issue by foolip** [GoogleChromeLabs/confluence#178]
@mdittmer, by scraping all IDL and also CSS specs, we should be able to attribute almost all APIs to some spec, and make standardization status part of the model. A useful metric we could create with this is a per-browser "non-standard APIs" metric.

It would also be useful for "failure to ship", "aggressive removal" and "browser-specific APIs", to differentiate between the two classes. In particular Firefox will have a lot of "failure to ship" for things that are non-standard, which is very different from being slow to add a new API that others have already shipped.

This is from discussion with @drufball and @gsnedders. @RByers FYI.

**Comment by foolip** [comment]
https://github.com/GoogleChrome/webidl-diff has some relevance to this, of course.

**Comment by mdittmer** [comment]
I like this idea. It sounds like this would involve Confluence consuming some data generated by WebIDL Diff, which is fine, but we're a ways away from deploying WebIDL Diff bots robust enough to open up their data.

**Comment by foolip** [comment]
The IDL data API wouldn't need to be public, it could be based on one-off runs where the data is committed to some repo, for example.

**Comment by foolip** [comment]
This would be some work, and we need some idea of how impactful it would be to have a "non-standard APIs" section. @bzbarsky @othermaciej, WDYT?

@RByers, who at Microsoft should we ask?

I think the stuff that's on the table is:
- Fixing known issues with the data (top prio)
- Making it faster, auto-updating and more user friendly (code health / product excellence)
- Adding or removing metrics/features to make it more actionable/useful (this issue, and also other metrics)

@mdittmer, did I forget something?

**Comment by othermaciej** [comment]
If an API is in all or almost all browsers, does it matter if it's not standard? Any API in 3 of 4 browsers that happens to not be standardized is likely to be a standards bug as well as a but in the 1 remaining browser.

Maybe it would be easier to think through this with concrete examples of non-standard APIs where a browser is being dinged for "failure to ship".

One possible exception is cases where browsers have copied each other's prefixed APIs, but maybe even those should be standardized in some way if truly needed for web compat.

I did have an idea of separately calling out "browser-specific APIs" that are a prefixed version of an API that's unprefixed in other browsers, but I guess that should be a separate issue.

**Comment by foolip** [comment]
@othermaciej, webkit-prefixed APIs implemented by Edge but not standardized are my main concern, as they'd show up on Firefox's "failure to ship". Currently listed are 5 APIs on CSSStyleDeclaration, lots that have to do with fullscreen, webkitCancelAnimationFrame/webkitRequestAnimationFrame, WebKitCSSMatrix.* and webkitURL.*.

Note that the two latter are standardized already:
https://drafts.fxtf.org/geometry/#DOMMatrix
https://url.spec.whatwg.org/#api

It's actually not as bad as I thought. What I would like is that *if* Firefox decides it should any of these, that the rest of us take on the burden of documenting what we do, instead of leaving it to @miketaylr to reverse engineer.

**Comment by RByers** [comment]
> This would be some work, and we need some idea of how impactful it would be to have a "non-standard APIs" section. @bzbarsky @othermaciej, WDYT?
> @RByers, who at Microsoft should we ask?

@patrickkettner drives interop efforts at Microsoft and may have input here.

I agree with @othermaciej that, strictly from a metrics perspective, standardization status doesn't really matter - we're just trying to measure interoperability here.  That's why (unlike the Edge API catalog this was modeled after, standardization status was not a priority for us).

But when I use this data to try to drive work within chromium, the standardization status totally influences my approach and which APIs I want to see listed.  Like @foolip, when I see Firefox failure-to-ship for something non-standard, I see it as (partly) our job to drive standardization.  Similarly, if we add the "in 2 only" metric (#120), then non-standard things in only chromium and WebKit are things I'd look into removing before suggesting standardization.

**Comment by othermaciej** [comment]
One possible way to represent this would be to have a a separate "failure to standardize" chart for all features that are in all but one browser but not in any standard.

**Comment by foolip** [comment]
Yeah, I think that would be reasonable. Whatever the specifics, having the standardization status as part of confluence would be required, and I'm now cooling on this idea.

Perhaps, instead, we should survey all APIs that aren't in all browsers, write some hacky scripts to filter out the stuff we know is standardized, until we have a list of all the non-standard APIs. A one-off is probably enough, and then we can take that list and make sure that bugs are filed and there are historical.html tests in wpt.

@mdittmer, WDYT? This could be a "wont fix" if we address the problem in some other way.

**Comment by othermaciej** [comment]
Thinking about it more, any feature that's in *all* browsers but not in any standard is also a potential standards bug.

**Comment by foolip** [comment]
Yes, that's definitely the case. I'm sure there are a few like that, but finding them isn't very high priority I'd argue. Sooner or later they will naturally come up if there's some interop problem, and if there isn't then we have more pressing interop issues to work on :)

**Comment by bzbarsky** [comment]
I think having a list of non-standard APIs that all, or all but one, browsers implement would be quite helpful as a guide to potential standardization.

One issue, and this is an issue with this whole dashboard, is that only presence, not correctness or interoperability, are tested.  This incentivizes addition of broken implementations to appease the metric, much like html5test.com....  I can only hope that people don't start using this dashboard as a marketing tool, and hence such pressure won't arise.

**Comment by foolip** [comment]
> I think having a list of non-standard APIs that all, or all but one, browsers implement would be quite helpful as a guide to potential standardization.

@mdittmer, how much work would it be to generate such a list as a one-off with the confluence + IDL data and a pile of scripts?

Hopefully this list will not grow much in the future, so maybe generating it once is good enough.

> One issue, and this is an issue with this whole dashboard, is that only presence, not correctness or interoperability, are tested. This incentivizes addition of broken implementations to appease the metric, much like html5test.com.... I can only hope that people don't start using this dashboard as a marketing tool, and hence such pressure won't arise.

Indeed. Just adding a standardization bit is not going to be enough to avoid this dynamic if people do start using it as a benchmark. Apart from such a bit, is there any change that would make a benchmark war less likely? Splitting the graphs by browser seems to be the most obvious to me, since one then has to do more work to figure out who is "winning."

**Comment by bzbarsky** [comment]
That might help.

Having titles that don't sound like a value judgement (e.g. not "failure to ship") might help too, maybe.

**Comment by foolip** [comment]
@mdittmer, what were some other titles we considered? "Last to support"?

**Comment by bzbarsky** [comment]
Just as much of a value judgement, fwiw.  I'm not sure what phrasing would work well there...

**Comment by othermaciej** [comment]
I agree with using a less judgmental term though I have no specific suggestions. "Aggressive removal" is a bit judgmental as well.

**Comment by foolip** [comment]
I filed https://github.com/GoogleChrome/confluence/issues/219, I guess let's leave this issue for the potential addition of standardization status.

**Comment by foolip** [comment]
BCD has a three statuses for each entry which could provide what this issue is asking for:
https://github.com/mdn/browser-compat-data/blob/master/schemas/compat-data-schema.md#status-information

I doubt it is entirely accurate, but I think that's the data we'd improve. The possibility of incorporating that into Confluence metrics remains, but I'm more inclined to pursue Confluence-style metrics based on BCD directly, so I'll close this as unlikely to see any action.
