### ISSUE TITLE
Bad data for Chrome 53?

### ISSUE THREAD

**Issue by RByers** [GoogleChromeLabs/confluence#205]
There's four different versions of Chrome 53 in the data set, and at least one (53.0.2785.89) seems to be [missing a lot of properties](http://web-confluence.appspot.com/#!/catalog?releaseKeys=%5B%22Chrome_53.0.2785.113_Windows_10.0%22,%22Chrome_53.0.2785.89_Windows_10.0%22%5D&releaseOptions=%7B%22Chrome_53.0.2785.113_Windows_10.0%22:true,%22Chrome_53.0.2785.89_Windows_10.0%22:false%7D&numAvailable=null&currentPage=0&gap=5&itemPerPage=15&searchKey=%22%22) (resulting in a weird dip on the API velocity graph).  Maybe some of these are beta builds? Should we just remove 3 of these data sets, keeping only whatever the latest crawl of Chrome 53 is?

**Comment by foolip** [comment]
We now have 3 versions of Chrome 53, and all were added after this issue:
https://github.com/mdittmer/web-apis/blob/master/data/og/window_Chrome_53.0.2785.113_Windows_10.0.json
https://github.com/mdittmer/web-apis/blob/master/data/og/window_Chrome_53.0.2785.89_OSX_10.11.6.json
https://github.com/mdittmer/web-apis/blob/master/data/og/window_Chrome_53.0.2785.97_Android_6.0.1.json
