### ISSUE TITLE
CSSStyleDeclaration.WebkitAlignSelf is claimed to be a Firefox-specific API

### ISSUE THREAD

**Issue by bzbarsky** [GoogleChromeLabs/confluence#235]
It's clearly present in Chrome, for example: `"WebkitAlignSelf" in document.body.style` tests true.

There's a bunch of these Webkit* bits on CSSStyleDeclaration that are incorrectly claimed to be Firefox-only.

**Comment by foolip** [comment]
Sounds like https://github.com/GoogleChromeLabs/confluence/issues/201

**Comment by mdittmer** [comment]
Thanks for the report, @bzbarsky! I'm closing this as being subsumed by #201
