### ISSUE TITLE
Add Edge 16 data

### ISSUE THREAD

**Issue by RByers** [GoogleChromeLabs/confluence#242]
It looks like BrowserStack has Edge 16 now.  Looking over some of the Edge "failure to ship" data with @arronei it seems like a lot has been fixed in Edge 16, so it would be nice to get that data.

**Comment by mdittmer** [comment]
This should be fixed when I push https://github.com/GoogleChrome/confluence/tree/r2017-11-11_00

**Comment by foolip** [comment]
We have Edge 16 data now. @mdittmer, please confirm that there isn't anything more to this issue.

**Comment by mdittmer** [comment]
We do have it. Although the rollout for it was actually inconsistent until I staged a release yesterday (so I'm glad it's now where it belongs in GCS).
