### ISSUE TITLE
Event prototype screwed up in Chrome

### ISSUE THREAD

**Issue by RByers** [GoogleChromeLabs/confluence#257]
Looking at the [Chrome failure to ship list](http://web-confluence.appspot.com/#!/catalog?releaseKeys=%5B%22Chrome_62.0.3202.62_Windows_10.0%22,%22Chrome_40.0.2214.93_Windows_10.0%22,%22Chrome_41.0.2272.89_Windows_10.0%22,%22Chrome_42.0.2311.135_Windows_10.0%22,%22Chrome_43.0.2357.81_Windows_10.0%22,%22Chrome_44.0.2403.89_Windows_10.0%22,%22Chrome_45.0.2454.85_Windows_10.0%22,%22Chrome_46.0.2490.71_Windows_10.0%22,%22Chrome_47.0.2526.73_Windows_10.0%22,%22Chrome_48.0.2564.97_Windows_10.0%22,%22Chrome_49.0.2623.75_Windows_10.0%22,%22Chrome_50.0.2661.75_Windows_10.0%22,%22Chrome_51.0.2704.79_Windows_10.0%22,%22Chrome_52.0.2743.82_Windows_10.0%22,%22Chrome_53.0.2785.113_Windows_10.0%22,%22Chrome_54.0.2840.59_Windows_10.0%22,%22Chrome_55.0.2883.75_Windows_10.0%22,%22Chrome_56.0.2924.87_Windows_10.0%22,%22Chrome_57.0.2987.110_Windows_10.0%22,%22Chrome_58.0.3029.81_Windows_10.0%22,%22Chrome_59.0.3071.86_Windows_10.0%22,%22Chrome_60.0.3112.78_Windows_10.0%22,%22Chrome_61.0.3163.79_Windows_10.0%22,%22Firefox_50.0_Windows_10.0%22,%22Firefox_51.0_Windows_10.0%22,%22Firefox_52.0_Windows_10.0%22,%22Firefox_53.0_Windows_10.0%22,%22Firefox_54.0_Windows_10.0%22,%22Firefox_55.0_Windows_10.0%22,%22Firefox_56.0_Windows_10.0%22,%22Edge_15.15063_Windows_10.0%22,%22Edge_16.16299_Windows_10.0%22,%22Safari_10.1.2_OSX_10.12.6%22,%22Safari_11.0_OSX_10.12.6%22%5D&releaseOptions=%7B%22Chrome_62.0.3202.62_Windows_10.0%22:false,%22Chrome_40.0.2214.93_Windows_10.0%22:false,%22Chrome_41.0.2272.89_Windows_10.0%22:false,%22Chrome_42.0.2311.135_Windows_10.0%22:false,%22Chrome_43.0.2357.81_Windows_10.0%22:false,%22Chrome_44.0.2403.89_Windows_10.0%22:false,%22Chrome_45.0.2454.85_Windows_10.0%22:false,%22Chrome_46.0.2490.71_Windows_10.0%22:false,%22Chrome_47.0.2526.73_Windows_10.0%22:false,%22Chrome_48.0.2564.97_Windows_10.0%22:false,%22Chrome_49.0.2623.75_Windows_10.0%22:false,%22Chrome_50.0.2661.75_Windows_10.0%22:false,%22Chrome_51.0.2704.79_Windows_10.0%22:false,%22Chrome_52.0.2743.82_Windows_10.0%22:false,%22Chrome_53.0.2785.113_Windows_10.0%22:false,%22Chrome_54.0.2840.59_Windows_10.0%22:false,%22Chrome_55.0.2883.75_Windows_10.0%22:false,%22Chrome_56.0.2924.87_Windows_10.0%22:false,%22Chrome_57.0.2987.110_Windows_10.0%22:false,%22Chrome_58.0.3029.81_Windows_10.0%22:false,%22Chrome_59.0.3071.86_Windows_10.0%22:false,%22Chrome_60.0.3112.78_Windows_10.0%22:false,%22Chrome_61.0.3163.79_Windows_10.0%22:false,%22Firefox_50.0_Windows_10.0%22:true,%22Firefox_51.0_Windows_10.0%22:true,%22Firefox_52.0_Windows_10.0%22:true,%22Firefox_53.0_Windows_10.0%22:true,%22Firefox_54.0_Windows_10.0%22:true,%22Firefox_55.0_Windows_10.0%22:true,%22Firefox_56.0_Windows_10.0%22:true,%22Edge_15.15063_Windows_10.0%22:true,%22Edge_16.16299_Windows_10.0%22:true,%22Safari_10.1.2_OSX_10.12.6%22:true,%22Safari_11.0_OSX_10.12.6%22:true%7D&numAvailable=null&currentPage=0&gap=5&itemPerPage=15&searchKey=%22%22), I see a lot of things apparently missing which are definitely on Event.prototype in Chrome (eg. `Event.preventDefault`). Looking at the API catalog I also see things on `Event` which shouldn't be there (eg. `Event.getRules` and `Event.dispatchToListener`), where are those coming from?

**Comment by foolip** [comment]
Hmm, there might be an actual problem here:
https://chromium.googlesource.com/chromium/src/+/65a2abd48ff21a19d3394c1200b9a632a642cdb7/extensions/renderer/resources/event.js#401
https://chromium.googlesource.com/chromium/src/+/65a2abd48ff21a19d3394c1200b9a632a642cdb7/extensions/renderer/resources/event.js#498

So `dispatchToListener` and `getRules` must have something to do with that script, but I can't see the properties myself. @mdittmer, can you see if you can reproduce these oddities when collecting manually, or could it be something about the BrowserStack setup that causes this script to be injected?

**Comment by mdittmer** [comment]
I suspect that this arises from the following truth in Chrome:

    window.chrome.webstore.onDownloadProgress.__proto__.constructor.name === window.Event.name

It's likely that [API Extractor](https://github.com/GoogleChromeLabs/confluence/blob/e1ec7594e6b37758dde7f0622e1d21983138fefd/lib/web_catalog/api_extractor.es6.js) isn't expecting two constructor+prototype pairs to map to the same interface name, and `window.chrome.webstore.onDownloadProgress.__proto__.constructor`'s API list is clobbering `window.Events`'s.

Further investigation still required.

**Comment by mdittmer** [comment]
Looks like I was right [this line](https://github.com/GoogleChromeLabs/confluence/blob/e1ec7594e6b37758dde7f0622e1d21983138fefd/lib/web_catalog/api_extractor.es6.js#L420) should be expanded to emit a warning if `apiCatalog[name]` already exists, and then perform a dedup-concat, rather than a clobber.
