### ISSUE TITLE
window.offscreenBuffering is missing

### ISSUE THREAD

**Issue by foolip** [GoogleChromeLabs/confluence#261]
Per https://bugs.chromium.org/p/chromium/issues/detail?id=438370 window.offscreenBuffering is in all engines except Gecko, but it cannot be found in the API catalog at http://web-confluence.appspot.com/. It does appear in the object graph data in https://github.com/mdittmer/web-apis however, so this is probably a bug in the post-processing.

**Comment by mdittmer** [comment]
This appears to be fixed: http://web-confluence.appspot.com/#!/catalog?releases=%5B%22Safari_11.1_OSX_10.13.4%22,%22Edge_17.17134_Windows_10.0%22,%22Firefox_61.0_Windows_10.0%22,%22Chrome_68.0.3440.75_Windows_10.0%22%5D&q=%22offscreen%22

**Comment by foolip** [comment]
Cool, thanks!
