### ISSUE TITLE
Define "Grace Period" and "can reasonably assume are still a part of the web...

### ISSUE THREAD

**Issue by tantek** [GoogleChromeLabs/confluence#288]
The Confluence Metrics graphs are quite interesting! It would be great if the "Grace Period" could be better defined, in particular, how do you qualify the start of a grace period?

Is it when the defining standard reaches a certain level of document maturity? E.g. W3C Recommmendation or at least Candidate Recommendation?

Or given the qualification "can reasonably assume are still a part of the web platform", is it based on there existing some number of Web Platform Tests for the API, and 2+ browsers passing them (in the same way)?

Either way it would be great to have a (at least somewhat) measurable / objective criteria, especially since the graphs make it look like the data is quite precise.

Thank you for providing such a great resource!

(Originally published at: http://tantek.com/2018/131/b1/)

**Comment by mdittmer** [comment]
Grace Period is explicitly defined [here](https://github.com/GoogleChromeLabs/confluence#the-metrics). For example, an API contributes to the "Browser-Specific" count for Browser X on Date D iff:

1. All releases of Browser X from Date D to Date D-1year include the API
1. All releases of other browsers (not Browser X) from Date D to Date D-1year do not include the API

**Comment by tantek** [comment]
I should have been more clear, it would be great if the Confluence Metrics graphs UI itself linked to the definition so it was more easily discoverable.

I.e. by putting a span with an ID on the definition of "Grace Period" in the README, and then linking to that fragment from the web UI, by hyperlinking the first instances of "Grace Period" (with quotes) appearing in the div class="text-content" elements in https://github.com/GoogleChromeLabs/confluence/blob/301782981ff6eeee30f4d272dcce6635ed09c943/static/view/confluence.html

I started a pull request at https://github.com/GoogleChromeLabs/confluence/pull/303 but figured you may have a more preferred method / markup for this.

Thanks for your consideration!

(Originally published at: http://tantek.com/2018/155/t2/)

**Comment by snarfed** [comment]
testing, 1 2 1 2 [ ](https://github.com/GoogleChromeLabs/confluence/issues/288#issuecomment-389209536) [](https://localhost:8080/publish/github)

(Originally published at: http://localhost/github_comment.html)
