### ISSUE TITLE
Chrome for macOS and Chrome for Windows have different results for Bluetooth APIs

### ISSUE THREAD

**Issue by connorshea** [GoogleChromeLabs/confluence#318]
[Link to Bluetooth API search](https://web-confluence.appspot.com/#!/catalog?releases=%5B%22Chrome_59.0.3071.86_OSX_10.11.6%22,%22Chrome_59.0.3071.86_Windows_10.0%22,%22Chrome_68.0.3440.75_OSX_10.13.6%22,%22Chrome_68.0.3440.75_Windows_10.0%22%5D&q=%22bluetooth%22)

Are Bluetooth APIs really supported on macOS but not Windows? 

<img width="1438" alt="screen shot 2018-08-30 at 2 28 09 pm" src="https://user-images.githubusercontent.com/2977353/44877362-f14d1a00-ac60-11e8-834c-fbe86af8eba8.png">

See also the [MDN Compat Table for `BluetoothRemoteGATTCharacteristic`](https://developer.mozilla.org/en-US/docs/Web/API/BluetoothRemoteGATTCharacteristic) which AFAIK is correct

**Comment by mdittmer** [comment]
That is basically correct. I just tested on a Windows laptop (in case using BrowserStack in the cloud was causing issues). Bluetooth APIs are, indeed, missing. The info [here](https://github.com/WebBluetoothCG/web-bluetooth/blob/gh-pages/implementation-status.md) explains that Bluetooth APIs are not enabled by default on Linux and Windows.

**Comment by mdittmer** [comment]
@connorshea would you be willing to file an issue to track this on https://github.com/mdn/browser-compat-data ?

**Comment by connorshea** [comment]
Yep, sorry for the incorrect issue!
