### ISSUE TITLE
Console has no data newer than November 2018

### ISSUE THREAD

**Issue by othermaciej** [GoogleChromeLabs/confluence#350]
The graphs at https://web-confluence.appspot.com/#!/ have no data points past November 2018.

**Comment by foolip** [comment]
I'll take care of collecting new data and updating. I'm afraid I don't have Safari 12.1 on my machine yet, and it's not on BrowserStack, but I'll find it somewhere!

**Comment by foolip** [comment]
@othermaciej https://confluence-f4ca39c--foam2-4e494ae-dot-web-confluence.appspot.com/ has Safari 12.1 if you want to filter the API catalog:
https://confluence-f4ca39c--foam2-4e494ae-dot-web-confluence.appspot.com/#!/catalog?releases=%5B%22Edge_18.17763_Windows_10.0%22,%22Chrome_73.0.3683.86_Windows_10.0%22,%22Firefox_66.0_Windows_10.0%22,%22Safari_12.1_OSX_10.13.6%22%5D&q=%22in:edge18%20in:chrome73%20in:firefox66%20notin:safari12.1%22

However, the graphs are broken so I'll have to look into that before updating https://web-confluence.appspot.com/#!/.

**Comment by foolip** [comment]
@othermaciej https://web-confluence.appspot.com/ is now deployed with new data from stable releases of all browsers, notably including Safari 12.1.

The significant drop in Safari lone omissions particularly encouraging:
![image](https://user-images.githubusercontent.com/498917/56381361-ea394300-6214-11e9-9089-6a92ab7a0e99.png)

The concrete list of APIs:
https://web-confluence.appspot.com/#!/catalog?releases=%5B%22Safari_12.0_OSX_10.13.6%22,%22Edge_18.17763_Windows_10.0%22,%22Chrome_73.0.3683.86_Windows_10.0%22,%22Firefox_66.0_Windows_10.0%22,%22Safari_12.1_OSX_10.13.6%22%5D&q=%22in:chrome73%20in:edge18%20in:firefox66%20notin:safari12.0%20in:safari12.1%22

Please let me know if you're having trouble making sense of any of the data or if you discover new issues with the methodology!
