### ISSUE TITLE
getBoxQuads is missing from the data

### ISSUE THREAD

**Issue by bzbarsky** [GoogleChromeLabs/confluence#481]
https://drafts.csswg.org/cssom-view/#geometryutils is implemented by at least Firefox but seems to be missing from the API data Confluence has.

**Comment by foolip** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/GeometryUtils suggests it's still behind a flag, is that wrong? (Unable to test myself right now.)

**Comment by bzbarsky** [comment]
Oh, good catch.  I thought it was enabled in release builds, but in fact it is not.  OK, then, sorry for the noise...
