### ISSUE TITLE
Vendor bundle has grown over time to >1.5MB

### ISSUE THREAD

**Issue by stephenmcgruer** [GoogleChromeLabs/confluence#568]
In https://github.com/GoogleChromeLabs/confluence/pull/567 Hexcles had to perform an emergency increase of the maxAssetSize and maxEntrypointSize to allow him to do a release of confluence. Obviously increasing the limit makes the idea of this being an error bar not that useful, so filing this so we don't forget that we did this :)

From that PR;

> I picked a few versions dating way back to Nov 1, 2018 (the last release by Mark). I'm seeing a steady increase of the vendor bundle size over time (about 30% gradually in the past two years). I think this bundle probably needs to be split into multiple chunks, but the front-end hard codes the asset URL.
> 
> All in all, this vendor bundle is still only ~400KiB when gzipped and this project is currently in maintenance mode. I might come back and revisit perhaps after fixing the more pressing performance issue of wpt.fyi...

This is very low priority, but if we come back to working on this then we likely need to split the bundle.

**Comment by foolip** [comment]
I shrank it down slightly again in https://github.com/GoogleChromeLabs/confluence/pull/649.

For now we're just preventing regressions. To make the the bundle size actually small would be a very large undertaking, as we'd need to get rid of the foam dependency, which is used for ~everything.
