### ISSUE TITLE
No data after October 2019?

### ISSUE THREAD

**Issue by domenic** [GoogleChromeLabs/confluence#584]
https://web-confluence.appspot.com/#!/confluence stops at October 2019, listing e.g. Chrome 78 as the latest version. Has something broken?

**Comment by stephenmcgruer** [comment]
Unfortunately data collection for confluence is currently scripted-but-manual (see e.g. https://github.com/mdittmer/web-apis/pull/93 and https://github.com/GoogleChromeLabs/confluence/pull/503), and usage of this project has been low enough historically that (a) updates fall very far behind, and (b) it has not been deemed worth it to automate updating (and then maintain the automation, which is the larger cost).

Can I ask what your use case is? I'm generally interested in what people are trying to use confluence for, as we're looking at potentially sunsetting it this year and I want to understand what might be lost.

**Comment by domenic** [comment]
There has recently been some Twitter kerfuffles claiming that browser X is shipping first, ahead of Candidate Recommendation or such, and that this is an unprecedented break in tradition. I find Confluence useful for finding both current and past counterexamples, via the "Browser-Specific" tab (see also #585). That is, it helps make it clear that advancing the web platform via shipping is something everyone does, and has done for a long time.

Concretely, I used that view to generate the following tweets: [1](https://mobile.twitter.com/domenic/status/1255880115030044677), [2](https://mobile.twitter.com/domenic/status/1255881535665901569), [3](https://mobile.twitter.com/domenic/status/1255881863123685377), [4](https://mobile.twitter.com/domenic/status/1255882121845051392) [5](https://mobile.twitter.com/domenic/status/1255882609185509378).

If #585 was fixed, or especially #482, I would also be able to link people to the relevant pages directly.

**Comment by othermaciej** [comment]
I would find fresher data useful for purposes of finding areas where WebKit might be behind on features, in a way that's easier to analyze than WPT results (which are much more fine grained and often hard to interpret).

**Comment by foolip** [comment]
I tried to collect data from Safari 13.1 and unfortunately managed to crash Safari, filed https://github.com/mdittmer/web-apis/issues/94 about that. I've sent https://github.com/mdittmer/web-apis/pull/95 with the data I collected for Chrome and Firefox, but that not as useful without Safari data too.

@stephenmcgruer what do you think we should do?

**Comment by stephenmcgruer** [comment]
Apologies for the delay here. I've been wondering if many of the insights desired here could be replaced by MDN's [browser-compat-data](https://github.com/mdn/browser-compat-data) project, if the data there was of higher quality. Currently it is missing quite a lot of data (see [an exploration I did recently](https://docs.google.com/document/d/1m4-HsHFleWflCYnwFN4R83c9ZqDgI5zS2Hpsnq6QMeQ/edit)), but we're hoping to invest in improving that data this year (we think it has a positive knock-on effect for interop via its use in MDN, visual studio, etc).

What I don't know yet is the diff between the data in BCD and the data here (maybe again there's an opportunity to auto-fill some BCD data using confluence?)

https://mdn-compat-data-explorer.herokuapp.com/ can be enlightening, although it's currently based on an older version of the BCD dataset.

**Comment by foolip** [comment]
I gave it another try to collect data using Safari 13.1.1, hoping that maybe the crash fix was in a patch release, but it still crashes.

**Comment by foolip** [comment]
I tried again on 13.1.2, still crashes.

**Comment by foolip** [comment]
Safari 14 was released today and I was able to collect new data: https://github.com/mdittmer/web-apis/pull/99

Working on updating Confluence now.

**Comment by foolip** [comment]
Alright, https://web-confluence.appspot.com/ has been updated, check it out!
