### ISSUE TITLE
Consider adding Modernizr data as "APIs"

### ISSUE THREAD

**Issue by RByers** [GoogleChromeLabs/confluence#75]
[Modernizr](https://modernizr.com) is a hand-curated list of [feature detects](https://modernizr.com/docs#features).  In many ways the status of each of these detects is as relevant to API confluence as the presence/absense of a JS API.  In some cases they're the same (eg. Modernizr.JSON is a [simple combination of JS API checks](https://github.com/Modernizr/Modernizr/blob/master/feature-detects/json.js) (and so redundant with our API confluence data), but in other cases they're much more interesting things that couldn't be automated generically (eg. [passive event listeners](https://github.com/Modernizr/Modernizr/blob/5eea7e2a213edc9e83a47b6414d0250468d83471/feature-detects/dom/passiveeventlisteners.js)).

I think it could be reasonable to just add ALL the Modernizr feature detects as additional "APIs" in our confluence list (though we might want an option to filter them out in some views).

/cc @patket

**Comment by foolip** [comment]
I looked into Modernizr a fair bit as a potential source for updating BCD, and found that a lot of them are trivial feature detects. Those would overlap with things already discovered by methods like Confluence's object graph discovery or tests generated from Web IDL or CSS syntax.

I ended up not pursuing it as it didn't seem to provide enough additional value, but if one wanted to use Modernizr data, I think it'd make the most sense as an input into BCD, not to augment the Confluence data set directly.
